data:
  num_sources: 3               # n
  num_channels: 5              # m
  duration: 2                  # t (seconds)
  sampling_frequency: 1000
  total_samples: 1000
  filter_type: 'g'
  train_split: 0.7
  val_split: 0.2

model:
  name: "Deconvolution"
  n_hidden: 64
  
training:
  batch_size: 32
  num_epochs: 10
  optimizer: "sgd"
  learning_rate: 0.001
  momentum: 0.5
  loss_function: "mse"
  hungarian_matching: True

validation:
  batch_size: 32

testing:
  batch_size: 32

experiment:
  random_seed: 0
  save: True 
  checkpoint_interval: 10    # Save every n epochs

logging:
  log_interval: 100