# Default configuration file
# Any parameters redifined in main.yaml will override these defaults.
# Parameters left null here are required to be set in main.yaml.


experiment:
  name: default_experiment
  random_seed: 42
  plot_examples: True
  save: True


data:
  name: null
  num_workers: 4
  curriculum:
    flag: false
    milestones: []
    parameters: {}


model:
  name: null
  checkpoint: null

training:
  optimizer: null
  batch_size: null
  epochs: null
  learning_rate: null
  momentum: null
  weight_decay: null
  patience: null
  val_split: null
  loss_function: null

validation:
  batch_size: null



evaluation:



inference:

